apiVersion: v1
kind: Service
metadata:
  name: mongo-service-api
  namespace: api
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
      name: mongo
  type: NodePort